// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7b8L54kR0rN1qtulVkzmSj30mpbZwN3U',
    appId: '1:861008742869:web:6f79deedf9de8ffb18955c',
    messagingSenderId: '861008742869',
    projectId: 'ecommerce-bfde3',
    authDomain: 'ecommerce-bfde3.firebaseapp.com',
    storageBucket: 'ecommerce-bfde3.appspot.com',
    measurementId: 'G-HM42KX3TZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChW5dKUuWg0a_zHB3JA-v5hgtsWsN2pv0',
    appId: '1:861008742869:android:13414cec1ed1a81618955c',
    messagingSenderId: '861008742869',
    projectId: 'ecommerce-bfde3',
    storageBucket: 'ecommerce-bfde3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQI4v5u6Me3eRUpUh4RoOCohVf0mVWM-4',
    appId: '1:861008742869:ios:e3002a0cb6cdd31a18955c',
    messagingSenderId: '861008742869',
    projectId: 'ecommerce-bfde3',
    storageBucket: 'ecommerce-bfde3.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQI4v5u6Me3eRUpUh4RoOCohVf0mVWM-4',
    appId: '1:861008742869:ios:e3002a0cb6cdd31a18955c',
    messagingSenderId: '861008742869',
    projectId: 'ecommerce-bfde3',
    storageBucket: 'ecommerce-bfde3.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7b8L54kR0rN1qtulVkzmSj30mpbZwN3U',
    appId: '1:861008742869:web:1b73ce3a9927fafb18955c',
    messagingSenderId: '861008742869',
    projectId: 'ecommerce-bfde3',
    authDomain: 'ecommerce-bfde3.firebaseapp.com',
    storageBucket: 'ecommerce-bfde3.appspot.com',
    measurementId: 'G-XZR32FVF2M',
  );
}
